### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'percentMovementChangeForTokenAtPoint')

### ISSUE THREAD

**Issue by yuri-ccp** [caewok/fvtt-elevation-ruler#100]
I'm getting this error when I move any token with this module enabled. Someone know anything about this?

TypeError: Cannot read properties of undefined (reading 'percentMovementChangeForTokenAtPoint')
    at TerrainMovePenaltyCenterGrid.moveMultiplier (MovePenalty.js:1007:25)
    at MovePenalty.js:1060:48
    at Array.reduce (<anonymous>)
    at MovePenalty.js:1060:22
    at MoveDistanceGridded.measure (MoveDistance.js:161:21)
    at MoveDistance.measure (MoveDistance.js:29:15)
    at _measureSegment (Ruler.js:362:28)
    at Ruler._computeSegmentDistances (Ruler.js:343:23)
    at Ruler._computeDistance (Ruler.js:284:28)
    at 🎁CONFIG.Canvas.rulerClass.prototype._computeDistance#0 (libWrapper-wrapper.js:187:52)
    at Ruler.measure (foundry.js:35790:10)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁CONFIG.Canvas.rulerClass.prototype.measure#aedifs-tactical-grid (settings.js:515:22)
    at 🎁CONFIG.Canvas.rulerClass.prototype.measure#0 (libWrapper-wrapper.js:187:52)
    at Ruler._onMouseMove (foundry.js:36402:10)
    at TokenPF2e._onDragLeftMove (Token.js:54:33)
    at 🎁CONFIG.Token.objectClass.prototype._onDragLeftMove#0 (libWrapper-wrapper.js:187:52)
    at MouseInteractionManager.callback (foundry.js:30532:17)
    at #handleDragMove (foundry.js:30911:26)
    at #handlePointerMove (foundry.js:30876:64)
    at vh.notifyListeners (EventBoundary.ts:1464:33)
    at vh.notifyTarget (EventBoundary.ts:658:14)
    at vh.propagate (EventBoundary.ts:310:18)
    at vh.dispatchEvent (EventBoundary.ts:210:14)
    at vh.mapPointerMove (EventBoundary.ts:815:64)
    at vh.mapEvent (EventBoundary.ts:231:28)
    at ra.onPointerMove (EventSystem.ts:396:31)

**Comment by ra2phoenix** [comment]
I had this issue while Terrain Mapper was enabled.  The two don't seem to work together just yet.

**Comment by caewok** [comment]
Thanks. Should be addressed in Terrain Mapper v0.3.2 along with Elevation Ruler v0.9.5.
