### ISSUE TITLE
Error with tactical grid

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-elevation-ruler#116]
https://ptb.discord.com/channels/915186263609454632/1193755370607345695/1257140842846752849

container.js:58 Uncaught TypeError: undefined. Cannot redefine property: center
[Detected 4 packages: aedifs-tactical-grid, lib-wrapper, elevationruler, walledtemplates]
    at Function.defineProperty (<anonymous>)
    at GridMaskContainer.drawMask (container.js:58:18)
    at 🎁CONFIG.Canvas.rulerClass.prototype._endMeasurement#aedifs-tactical-grid (settings.js:540:64)
    at 🎁CONFIG.Canvas.rulerClass.prototype._endMeasurement#0 (libWrapper-wrapper.js:189:48)
    at Ruler._onMouseUp (foundry.js:36582:12)
    at CONFIG.Token.objectClass._onDragLeftCancel (Token.js:53:69)
    at CONFIG.Token.objectClass._onDragLeftCancel (Token.js:323:3)

**Comment by caewok** [comment]
Fixed in v0.9.7.
