### ISSUE TITLE
#107 but with different error code

### ISSUE THREAD

**Issue by Danii0206** [caewok/fvtt-elevation-ruler#117]
Hi,

I still get the behaviour of issue #107 in version 0.9.6, but with a different error code:
```
libWrapper-wrapper.js:513 Uncaught Error: Flag scope "terrainmapper" is not valid or not currently active
    at ScenePF2e.getFlag (foundry-esm.js:11771:44)
    at Ruler._addWaypoint (Ruler.js:157:70)
    at 🎁CONFIG.Canvas.rulerClass.prototype._addWaypoint#0 (libWrapper-wrapper.js:187:52)
    at Ruler._startMeasurement (foundry.js:36051:10)
    at Ruler._onDragStart (foundry.js:36512:10)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at Ruler._onDragStart (Ruler.js:398:10)
    at 🎁CONFIG.Canvas.rulerClass.prototype._onDragStart#0 (libWrapper-wrapper.js:187:52)
    at #onDragLeftStart (foundry.js:25733:34)
    at MouseInteractionManager.callback (foundry.js:30691:17)
    at #handleDragStart (foundry.js:31053:15)
    at #handlePointerMove (foundry.js:31031:43)
    at vh.notifyListeners (EventBoundary.ts:1464:33)
    at vh.notifyTarget (EventBoundary.ts:658:14)
    at vh.propagate (EventBoundary.ts:310:18)
    at vh.dispatchEvent (EventBoundary.ts:210:14)
    at vh.mapPointerMove (EventBoundary.ts:815:64)
    at vh.mapEvent (EventBoundary.ts:231:28)
    at ra.onPointerMove (EventSystem.ts:396:31)
```
Is terrain mapper a dependency for elevation ruler?

Edit: With Terrain mapper installed, it works.

**Comment by Danii0206** [comment]
This is the same as #115 . Sorry, did not see it before. Will close this.
