### ISSUE TITLE
Errors when Terrain Mapper module active.

### ISSUE THREAD

**Issue by GambetTV** [caewok/fvtt-elevation-ruler#169]
The latest version of Elevation Ruler (v0.10.0) seems to bug out when Terrain Mapper is active, even if there is no terrain on the map. A single Region placed on the map, even if it's not set as terrain, causes multiple console errors to fire off when you drag your token, and the ruler is not displayed during the token drag anymore.

> libWrapper-wrapper.js:513 Uncaught TypeError: Cannot read properties of undefined (reading 'hasTerrain')
    at MovePenalty.js:71:28
    at Array.forEach (<anonymous>)
    at new MovePenalty (MovePenalty.js:70:49)
    at Ruler._computeSegmentDistances (segments.js:38:57)
    at Ruler._computeDistance (Ruler.js:380:28)
    at 🎁CONFIG.Canvas.rulerClass.prototype._computeDistance#0 (libWrapper-wrapper.js:187:52)
    at Ruler.measure (foundry.js:36092:10)
    at Ruler._addWaypoint (Ruler.js:226:8)
    at 🎁CONFIG.Canvas.rulerClass.prototype._addWaypoint#0 (libWrapper-wrapper.js:187:52)
    at Ruler._startMeasurement (foundry.js:36191:10)
    at Ruler._onDragStart (foundry.js:36658:10)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at Ruler._onDragStart (Ruler.js:614:10)
    at 🎁CONFIG.Canvas.rulerClass.prototype._onDragStart#0 (libWrapper-wrapper.js:187:52)
    at Token5e._onDragLeftStart (Token.js:159:25)
    at 🎁CONFIG.Token.objectClass.prototype._onDragLeftStart#0 (libWrapper-wrapper.js:187:52)
    at MouseInteractionManager.callback (foundry.js:30823:17)
    at #handleDragStart (foundry.js:31185:15)
    at #handlePointerMove (foundry.js:31163:43)
    at vh.notifyListeners (EventBoundary.ts:1464:33)
    at vh.notifyTarget (EventBoundary.ts:658:14)
    at vh.propagate (EventBoundary.ts:310:18)
    at vh.dispatchEvent (EventBoundary.ts:210:14)
    at vh.mapPointerMove (EventBoundary.ts:815:64)
    at vh.mapEvent (EventBoundary.ts:231:28)
    at ra.onPointerMove (EventSystem.ts:396:31)

**Comment by GambetTV** [comment]
Apologies, I was wrong. I freshly installed Terrain Mapper assuming that would be the most recent version, but it was not. Upon updating the module, it went to the correct version and I no longer ran into the problem.

**Comment by caewok** [comment]
Yeah, that one is on me. I had not yet updated the Foundry package listing, so it was giving you the older Terrain Mapper on fresh install.
