### ISSUE TITLE
DnD 4e system support

### ISSUE THREAD

**Issue by LordCracken** [caewok/fvtt-elevation-ruler#213]
I wanted to try this module for my DnD 4e game and encountered couple of issues: 

1) Ruler doesn't appear
2) As GM I still can use module functional such as teleportation, changing elevation or placing waypoints. As Player I can't do this. 
3) There also default ruler disappears. Looks like ruler settings of module and system are conflicting

It will be great if the module is compatible with the DnD 4e system. Earlier Drag Ruler were compatible with DnD 4e, there was four states of ruler: walk, run, double walk, double run.

If you need additional info let me know.

**Comment by caewok** [comment]
Try v0.10.13.

**Comment by LordCracken** [comment]
Thank  you very much! It works now

**Comment by warforged44** [comment]
I'm testing Foundry v12.331, Elevation Ruler v0.10.13, and DnD4e v0.5.4. I'm experiencing similar issues still. With "Round Distance to Multiple" set to 0.1, I get the following error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'toNearest')
[Detected 2 packages: elevationruler(0.10.13), lib-wrapper(1.13.2.0)]
    at roundMultiple (util.js:288:28)
    at Ruler._getSegmentLabel (Ruler.js:506:22)
    at 🎁CONFIG.Canvas.rulerClass.prototype._getSegmentLabel#0 (libWrapper-wrapper.js:191:52)
    at Ruler._drawMeasuredPath (foundry.js:36334:27)
    at Ruler.measure (foundry.js:36108:10)
    at Ruler._onMouseMove (foundry.js:36719:10)
    at #onDragLeftMove (foundry.js:25913:67)
    at MouseInteractionManager.callback (foundry.js:30834:17)
    at #handleDragMove (foundry.js:31213:26)
    at #handlePointerMove (foundry.js:31178:64)
    at vh.notifyListeners (EventBoundary.ts:1464:33)
    at vh.notifyTarget (EventBoundary.ts:658:14)
    at vh.propagate (EventBoundary.ts:310:18)
    at vh.dispatchEvent (EventBoundary.ts:210:14)
    at vh.mapPointerMove (EventBoundary.ts:815:64)
    at vh.mapEvent (EventBoundary.ts:231:28)
    at ra.onPointerMove (EventSystem.ts:396:31)
```

If I set the Round Distance to 0, I get the following instead:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'almostEqual')
[Detected 2 packages: elevationruler(0.10.13), lib-wrapper(1.13.2.0)]
    at segmentTerrainLabel (segment_labels_highlighting.js:138:24)
    at basicTextLabel (segment_labels_highlighting.js:174:47)
    at Ruler._getSegmentLabel (Ruler.js:521:10)
    at 🎁CONFIG.Canvas.rulerClass.prototype._getSegmentLabel#0 (libWrapper-wrapper.js:191:52)
    at Ruler._drawMeasuredPath (foundry.js:36334:27)
    at Ruler.measure (foundry.js:36108:10)
    at Ruler._onMouseMove (foundry.js:36719:10)
    at #onDragLeftMove (foundry.js:25913:67)
    at MouseInteractionManager.callback (foundry.js:30834:17)
    at #handleDragMove (foundry.js:31213:26)
    at #handlePointerMove (foundry.js:31178:64)
    at vh.notifyListeners (EventBoundary.ts:1464:33)
    at vh.notifyTarget (EventBoundary.ts:658:14)
    at vh.propagate (EventBoundary.ts:310:18)
    at vh.dispatchEvent (EventBoundary.ts:210:14)
    at vh.mapPointerMove (EventBoundary.ts:815:64)
    at vh.mapEvent (EventBoundary.ts:231:28)
    at ra.onPointerMove (EventSystem.ts:396:31)
segmentTerrainLabel @ segment_labels_highlighting.js:138
basicTextLabel @ segment_labels_highlighting.js:174
_getSegmentLabel @ Ruler.js:521
🎁CONFIG.Canvas.rulerClass.prototype._getSegmentLabel#0 @ libWrapper-wrapper.js:191
_drawMeasuredPath @ foundry.js:36334
measure @ foundry.js:36108
_onMouseMove @ foundry.js:36719
#onDragLeftMove @ foundry.js:25913
callback @ foundry.js:30834
#handleDragMove @ foundry.js:31213
#handlePointerMove @ foundry.js:31178
notifyListeners @ EventBoundary.ts:1464
notifyTarget @ EventBoundary.ts:658
propagate @ EventBoundary.ts:310
dispatchEvent @ EventBoundary.ts:210
mapPointerMove @ EventBoundary.ts:815
mapEvent @ EventBoundary.ts:231
onPointerMove @ EventSystem.ts:396
```

In my testing setup, no other modules are enabled, only Elevation Ruler and libWrapper (1.13.2.0).
