### ISSUE TITLE
Ruler Tool Non Functional With PF2e 

### ISSUE THREAD

**Issue by hubbaben** [caewok/fvtt-elevation-ruler#46]
Get the following error when attempting to use the ruler tool while a token is on the scene's canvas. No modules aside from elevation ruler and libwrapper are enabled. 

Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
    at terrain_elevation.js:123:45
    at Array.filter (<anonymous>)
    at Ruler.elevationAtLocation (terrain_elevation.js:123:8)
    at elevateSegments (segments.js:323:47)
    at Ruler._getMeasurementSegments (segments.js:40:20)
    at 🎁CONFIG.Canvas.rulerClass.prototype._getMeasurementSegments#0 (libWrapper-wrapper.js:187:52)
    at Ruler.measure (foundry.js:37154:26)
    at Ruler._onMouseMove (foundry.js:37541:12)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at Ruler._onMouseMove (Ruler.js:496:10)
    at 🎁CONFIG.Canvas.rulerClass.prototype._onMouseMove#0 (libWrapper-wrapper.js:187:52)
    at Canvas._onDragLeftMove (foundry.js:27449:42)
    at MouseInteractionManager.callback (foundry.js:31766:17)
    at #handleDragMove (foundry.js:32113:26)
    at #handleMouseMove (foundry.js:32085:37)
    at Na.notifyListeners (earcut.js:128:75)
    at Na.notifyTarget (earcut.js:128:75)
    at Na.propagate (earcut.js:128:75)
    at Na.dispatchEvent (earcut.js:128:75)
    at Na.mapPointerMove (earcut.js:128:75)
    at Na.mapEvent (earcut.js:128:75)
    at yn.onPointerMove (earcut.js:128:75)

**Comment by caewok** [comment]
I think this is fixed in v0.8.5.
